[workspace]
authors = ["Sergey Mikhno <sergey.mikhno@gmail.com>"]
channels = ["conda-forge"]
name = "segmentation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pytorch = ">=2.9.1,<3"
numpy = ">=2.3.5,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
jupyterlab = ">=4.5.0,<5"
ipywidgets = ">=8.1.8,<9"
shapely = ">=2.1.2,<3"
black = ">=25.1.0,<26"

[system-requirements]
cuda = "13.0"

[pypi-dependencies]
python-doctr = ">=1.0.0, <2"
opencv-python = ">=4.11.0.86, <5"
